// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_chat_app/test/states/receipt_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chat/src/models/receipt.dart' as _i4;
import 'package:chat/src/models/user.dart' as _i5;
import 'package:chat/src/services/receipt/receipt_service_contract.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IReceiptService].
///
/// See the documentation for Mockito's code generation for more information.
class FakeReceiptService extends _i1.Mock implements _i2.IReceiptService {
  @override
  _i3.Future<bool> send(_i4.Receipt? receipt) => (super.noSuchMethod(
        Invocation.method(
          #send,
          [receipt],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Stream<_i4.Receipt> receipts(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #receipts,
          [user],
        ),
        returnValue: _i3.Stream<_i4.Receipt>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.Receipt>.empty(),
      ) as _i3.Stream<_i4.Receipt>);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
